### ISSUE TITLE
NetworkOnMainThreadException

### ISSUE THREAD

**Issue by alexblack** [thiagolocatelli/android-stripe-connect#3]
When I try to connect and skip account-form (in dev mode) I get this exception:

(Also, it doesn't call onError...)

My code:

```
final StripeApp stripe = new StripeApp(
        this,
        Constant.STRIPE_ACCOUNT_NAME,
        Constant.STRIPE_CLIENT_ID,
        Constant.STRIPE_CLIENT_SECRET,
        Constant.STRIPE_CALLBACK_URL,
        Constant.STRIPE_READ_WRITE
    );

    final TextView stripeSummary = (TextView) findViewById(R.id.stripeSummary);

    btnStripe = (StripeButton) findViewById(R.id.btnStripeConnect);
    btnStripe.setStripeApp(stripe);
    btnStripe.setConnectMode(StripeApp.CONNECT_MODE.ACTIVITY);
```

Exception:

```
01-18 20:28:25.168  12766-12766/com.aadhk.woinvoice W/System.err﹕ android.os.NetworkOnMainThreadException
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at java.net.InetAddress.getAllByName(InetAddress.java:215)
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:272)
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
01-18 20:28:25.179  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
01-18 20:28:25.184  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
01-18 20:28:25.184  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
01-18 20:28:25.184  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.github.thiagolocatelli.stripe.StripeUtils.executePost(StripeUtils.java:59)
01-18 20:28:25.184  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.github.thiagolocatelli.stripe.StripeActivity.getAccessToken(StripeActivity.java:148)
01-18 20:28:25.184  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.github.thiagolocatelli.stripe.StripeActivity.onComplete(StripeActivity.java:181)
01-18 20:28:25.184  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.github.thiagolocatelli.stripe.StripeActivity.access$200(StripeActivity.java:22)
01-18 20:28:25.184  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.github.thiagolocatelli.stripe.StripeActivity$OAuthWebViewClient.shouldOverrideUrlLoading(StripeActivity.java:100)
01-18 20:28:25.184  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:339)
01-18 20:28:25.184  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:261)
01-18 20:28:25.184  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
01-18 20:28:25.184  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:28)
01-18 20:28:25.185  12766-12766/com.aadhk.woinvoice W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
01-18 20:28:25.185  12766-12766/com.aadhk.woinvoice W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
01-18 20:28:25.185  12766-12766/com.aadhk.woinvoice W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5221)
01-18 20:28:25.185  12766-12766/com.aadhk.woinvoice W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
01-18 20:28:25.185  12766-12766/com.aadhk.woinvoice W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
01-18 20:28:25.185  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
01-18 20:28:25.185  12766-12766/com.aadhk.woinvoice W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by alexblack** [comment]
Changing the code in StripeActivity.onComplete seems to have fixed it:

```
private void onComplete(Map<String, String> parameters) {       
  final String code = parameters.get("code");

    new Thread() {
      @Override
      public void run() {
        getAccessToken(code);
        Intent returnIntent = new Intent();
        setResult(StripeApp.RESULT_CONNECTED, returnIntent);
        finish();
      }
    }.start();
}
```

**Comment by Lemonlemons** [comment]
I had the same problem and above solution worked for me too, right on!
